
name: Azure Static Website CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --container-name '$web' --overwrite true --file index.html
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --container-name '$web' --overwrite true --file styles.css
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCESS_KEY }} --container-name '$web' --overwrite true --file script.js
    
    - name: Purge Azure CDN
      uses: azure/cli@v1
      with:
        inlineScript: |
          az cdn endpoint purge --resource-group rrr-personal-space --profile-name rrr-CDN-classic --name cvryanrothwell --content-paths '/*'
